blank_issues_enabled: false
contact_links:
  - name: Ask a question about volantis or get support
    url: https://github.com/volantis-x/hexo-theme-volantis/discussions/new
    about: Ask a question or request support for using volantis
  - name: Ask a question related to hexo but not about volantis
    url: https://github.com/hexojs/hexo/issues
    about: Ask a question about the hexo but not about volantis